/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#000000",
          "primary-content": "#ffffff",
          secondary: "#333333",
          "secondary-content": "#ffffff",
          accent: "#666666",
          "accent-content": "#ffffff",
          neutral: "#111111",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f5f5f5",
          "base-300": "#e0e0e0",
          "base-content": "#000000",
          info: "#000000",
          success: "#000000",
          warning: "#000000",
          error: "#000000",
          "--rounded-btn": "0.25rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
          ".btn": { 
            "text-transform": "none",
            "font-weight": "normal",
          },
        },
      },
      {
        dark: {
          primary: "#ffffff",
          "primary-content": "#000000",
          secondary: "#cccccc",
          "secondary-content": "#000000",
          accent: "#888888",
          "accent-content": "#000000",
          neutral: "#dddddd",
          "neutral-content": "#000000",
          "base-100": "#121212",
          "base-200": "#1e1e1e",
          "base-300": "#2a2a2a",
          "base-content": "#ffffff",
          info: "#ffffff",
          success: "#ffffff",
          warning: "#ffffff",
          error: "#ffffff",
          "--rounded-btn": "0.25rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
          ".btn": { 
            "text-transform": "none",
            "font-weight": "normal",
          },
        },
      },
    ],
  },
  theme: {
    extend: {
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};